#!/usr/bin/env node
import {
  intro,
  text,
  spinner,
  note,
  outro,
  isCancel,
  cancel,
} from "@clack/prompts";
import chalk from "chalk";
import gradient from "gradient-string";
import yargs from "yargs/yargs";
import { hideBin } from "yargs/helpers";
import fs from "fs/promises";
import path from "path";
import prettier from "prettier";
import { parseCurlOrUrl } from "./utils/curl-parser.js";
import { fetchNetworkData } from "./services/network.js";
import { generateCode, type ClientType } from "./services/generator.js";
import { renderResult } from "./ui/ResultViewer.js";
import {
  validateSafePath,
  sanitizeErrorMessage,
} from "./utils/security.js";

async function detectClientType(): Promise<ClientType> {
  try {
    const pkgPath = path.join(process.cwd(), "package.json");
    const pkgJson = await fs.readFile(pkgPath, "utf-8");
    const pkg = JSON.parse(pkgJson);
    const deps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };

    if (deps.axios) return "axios";
    if (deps.ofetch) return "ofetch";
    if (deps.ky) return "ky";
    if (deps.got) return "got";
  } catch {
    // Ignore errors (no package.json or invalid json)
  }
  return "fetch";
}

async function main() {
  console.clear();

  const welcomeText = `
     ______                __     ______          ______          __
    / ____/___  _________ / /    /_  __/___      / ____/___  ____/ /__
   / /   / __ \\/ ___/ __ \`/ /      / / / __ \\    / /   / __ \\/ __  / _ \\
  / /___/ /_/ / /  / /_/ / /      / / / /_/ /   / /___/ /_/ / /_/ /  __/
  \\____/\\____/_/   \\__,_/_/      /_/  \\____/    \\____/\\____/\\__,_/\\___/
  `;

  console.log(gradient.pastel(welcomeText));

  // ─── CLI argument parsing ───────────────────────────────────────────
  const argv = await yargs(hideBin(process.argv))
    .option("url", {
      alias: "u",
      type: "string",
      description: "URL or cURL command to extract data from",
    })
    .option("output", {
      alias: "o",
      type: "string",
      description:
        "Path to write the generated code (e.g., ./src/models.ts)",
    })
    .option("allow-private", {
      type: "boolean",
      default: false,
      description:
        "Allow requests to private/local network addresses (e.g., localhost, 10.x.x.x)",
    })
    .option("timeout", {
      alias: "t",
      type: "number",
      default: 15,
      description: "Network request timeout in seconds",
    })
    .option("client", {
      alias: "c",
      choices: ["fetch", "axios", "ky", "got", "ofetch"],
      type: "string",
      description: "HTTP client to generate code for (auto-detected if omitted)",
    })
    .help()
    .alias("help", "h")
    .version()
    .alias("version", "v").argv;

  let input: string | symbol = argv.url || "";

  if (!input) {
    intro(chalk.bgCyan.black(" CURL-TO-CODE "));

    input = await text({
      message: "Enter a URL or cURL command to extract data from:",
      placeholder: 'curl https://api.example.com/data -H "Bearer token"',
      validate(value) {
        if (!value || value.trim().length === 0) return "Input is required";
      },
    });

    if (isCancel(input)) {
      cancel("Operation cancelled.");
      process.exit(0);
    }
  } else {
    console.log(chalk.cyan(`> Using provided input: ${input}`));
  }

  const s = spinner();
  s.start("Parsing input and preparing network link");

  try {
    const requestConfig = await parseCurlOrUrl(input as string, {
      allowPrivate: argv["allow-private"] as boolean,
    });

    s.message(`Connecting to ${chalk.green(requestConfig.url)}`);
    const data = await fetchNetworkData(requestConfig, {
      allowPrivate: argv["allow-private"] as boolean,
      timeoutMs: ((argv.timeout as number) || 15) * 1000,
    });

    const clientType = (argv.client as ClientType) || (await detectClientType());

    s.message(`Crystallizing JSON payload into TypeScript and Zod schemas (Client: ${clientType})`);
    const generated = generateCode(data, requestConfig, clientType);

    s.stop(`Extraction complete for ${chalk.green(requestConfig.url)}`);

    // ─── File output ────────────────────────────────────────────────
    if (argv.output) {
      const rawOutputPath = argv.output as string;
      const safeOutputPath = validateSafePath(rawOutputPath);
      s.start(`Writing and formatting output to ${safeOutputPath}`);

      const fileContent = `// Generated by curl-to-code\n// Source: ${requestConfig.url}\n// Date: ${new Date().toISOString()}\nimport { z } from "zod";\n\n${generated.typeScript}\n\n${generated.zod}\n\n${generated.fetchClient}\n`;

      const formatted = await prettier.format(fileContent, {
        parser: "typescript",
      });

      await fs.mkdir(path.dirname(safeOutputPath), { recursive: true });
      await fs.writeFile(safeOutputPath, formatted, "utf-8");

      s.stop(
        chalk.green(`Successfully wrote API types to ${safeOutputPath}`),
      );
    }

    renderResult(data, generated);

    outro(gradient.pastel("Code generated successfully!"));
  } catch (error: unknown) {
    s.stop(chalk.red("Extraction failed"));
    note(chalk.redBright(sanitizeErrorMessage(error)), "Error Details");
    process.exit(1);
  }
}

main().catch(console.error);
