#!/usr/bin/env node
import {
  intro,
  text,
  spinner,
  note,
  outro,
  isCancel,
  cancel,
} from "@clack/prompts";
import chalk from "chalk";
import gradient from "gradient-string";
import yargs from "yargs/yargs";
import { hideBin } from "yargs/helpers";
import fs from "fs/promises";
import path from "path";
import prettier from "prettier";
import { parseCurlOrUrl } from "./utils/curl-parser";
import { fetchNetworkData } from "./services/network";
import { generateCode } from "./services/generator";
import { renderResult } from "./ui/ResultViewer.js";
import { validateSafePath } from "./utils/security.js";

async function main() {
  console.clear();

  const welcomeText = `
     ______                __     ______          ______          __
    / ____/___  _________ / /    /_  __/___      / ____/___  ____/ /__
   / /   / __ \\/ ___/ __ \`/ /      / / / __ \\    / /   / __ \\/ __  / _ \\
  / /___/ /_/ / /  / /_/ / /      / / / /_/ /   / /___/ /_/ / /_/ /  __/
  \\____/\\____/_/   \\__,_/_/      /_/  \\____/    \\____/\\____/\\__,_/\\___/
  `;

  console.log(gradient.pastel(welcomeText));

  // Parse command line arguments
  const argv = await yargs(hideBin(process.argv))
    .option("url", {
      alias: "u",
      type: "string",
      description: "URL or cURL command to extract data from",
    })
    .option("output", {
      alias: "o",
      type: "string",
      description: "Path to write the generated code (e.g., ./src/models.ts)",
    })
    .help()
    .alias("help", "h").argv;

  let input: string | symbol = argv.url || "";

  if (!input) {
    intro(chalk.bgCyan.black(" THE NETWORK-TO-CODE VISUALIZER "));

    input = await text({
      message: "Enter a URL or cURL command to extract data from:",
      placeholder: 'curl https://api.example.com/data -H "Bearer token"',
      validate(value) {
        if (!value || value.trim().length === 0) return "Input is required";
      },
    });

    if (isCancel(input)) {
      cancel("Hologram extraction aborted.");
      process.exit(0);
    }
  } else {
    console.log(chalk.cyan(`> Using provided input: ${input}`));
  }

  const s = spinner();
  s.start("Parsing input and preparing network link");

  try {
    const requestConfig = parseCurlOrUrl(input as string);

    s.message(`Connecting to ${chalk.green(requestConfig.url)}`);
    const data = await fetchNetworkData(requestConfig);

    s.message("Crystallizing JSON payload into TypeScript and Zod schemas");
    // Pass full request config to generate the fetch client as well
    const generated = generateCode(data, requestConfig);

    s.stop(`Extraction complete for ${chalk.green(requestConfig.url)}`);

    if (argv.output) {
      const rawOutputPath = argv.output as string;
      const safeOutputPath = validateSafePath(rawOutputPath);
      s.start(`Writing and formatting output to ${safeOutputPath}`);
      
      const fileContent = `// Generated by Hologram API\nimport { z } from "zod";\n\n${generated.typeScript}\n\n${generated.zod}\n\n${generated.fetchClient}\n`;
      
      const formatted = await prettier.format(fileContent, {
        parser: "typescript",
      });

      await fs.mkdir(path.dirname(safeOutputPath), { recursive: true });
      await fs.writeFile(safeOutputPath, formatted, "utf-8");
      
      s.stop(chalk.green(`Successfully wrote API types to ${safeOutputPath}`));
    }

    renderResult(data, generated);

    outro(gradient.pastel("Hologram generated successfully!"));
  } catch (error: any) {
    s.stop(chalk.red("Extraction failed"));
    note(chalk.redBright(error.message), "Error Details");
    process.exit(1);
  }
}

main().catch(console.error);
